### ISSUE TITLE
entered value is not working ??

### ISSUE THREAD

**Issue by manojbetma** [geersch/bootstrap-spinedit#25] opened 2014-09-23 02:00 UTC
Hello ,
this is relay nice.
but i found a bug , 
if you enter any number value using keyboard and then you do any incr or descr operation , it will not work , it work with old value , not work with entered by keyboard.

Thank you.

**Comment by geersch** [comment] 2022-01-26 14:37
Duplicate of https://github.com/geersch/bootstrap-spinedit/issues/12

**Closed by geersch** 2022-01-26 14:37 UTC
